=== florianklockenkemper/psh/resource/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="psh" type="pshConfig"/>

    <xs:complexType name="pshConfig">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="header" type="xs:string"/>
            <xs:element name="import" type="import"/>
            <xs:element name="placeholder" type="vars"/>

            <xs:element name="path" type="xs:string"/>
            <xs:element name="template" type="template"/>
            <xs:element name="environment" type="environment" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="environment">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="placeholder" type="vars" />
            <xs:element name="path" type="xs:string"/>
            <xs:element name="template" type="template"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="hidden" type="xs:boolean" default="false" />
    </xs:complexType>

    <xs:complexType name="template">
        <xs:attribute name="source" type="xs:string" use="required"/>
        <xs:attribute name="destination" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="vars">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="const" type="var" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dynamic" type="var" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="dotenv" type="pathvar" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="require" type="requirevar" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="var">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="pathvar">
        <xs:simpleContent>
            <xs:extension base="xs:string">
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="requirevar">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="description" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="import">
        <xs:attribute name="path" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== florianklockenkemper/psh/tests/Acceptance/_app/.psh.xml
<?xml version="1.0" encoding="UTF-8"?>
<psh xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../resource/config.xsd">

    <header>SHOPWARE PHP-SH</header>
    <template source="templates/test.tpl" destination="result.txt"/>
    <path>scripts/</path>
    <placeholder>
        <const name="ENV">prod</const>
        <const name="TEST">prod</const>
        <dynamic name="ID">id</dynamic>
        <dynamic name="LL">ls -ahl</dynamic>
        <dotenv>.env</dotenv>
        <require name="DOTENV" description="The env var is missing"/>
        <require name="TEST" description="The test var is missing"/>
        <require name="ID"/>
    </placeholder>
    <environment name="test">
        <path>envpath/</path>
        <path>envpath2/</path>
        <placeholder>
            <const name="ENV">test</const>
        </placeholder>
    </environment>
    <environment name="hidden" hidden="true">
        <path>envpath/</path>
        <path>envpath2/</path>
        <placeholder>
            <const name="ENV">hidden</const>
        </placeholder>
    </environment>
</psh>
